server:
  port: 9000

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${AUTH_DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  rsa:
    public-key: ${RSA_PUBLIC_KEY}
    private-key: ${RSA_PRIVATE_KEY}

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL}       # Ví dụ: http://localhost:5173
    redirect-uri: ${FRONTEND_REDIRECT_URI} # Callback login
  
  oauth2:
    client-id: ${OAUTH_CLIENT_ID}
    client-secret: ${OAUTH_CLIENT_SECRET}
    postman-redirect: ${OAUTH_POSTMAN_REDIRECT}
    # Danh sách các URL được phép quay về sau khi logout (phân cách bằng dấu phẩy nếu chạy docker/env)
    post-logout-uris: ${OAUTH_POST_LOGOUT_URIS} 
  
  cors:
    # Danh sách các domain được phép gọi API (CORS)
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

