apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-deployment
  namespace: meeting-system
  labels:
    app: oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: gk123a/auth:v2 # Image của bạn
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          
          # Nạp toàn bộ biến môi trường từ ConfigMap và Secret
          envFrom:
            - configMapRef:
                name: oauth-config
            - secretRef:
                name: oauth-secrets
          
          # Cấu hình JDBC (Ghép từ các biến lẻ thành chuỗi kết nối)
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: oauth-config
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth-secrets
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 800m
              memory: 512Mi