# 1. Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: oauth-svc
  namespace: meeting-system
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: oauth

---
# 2. Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth-ingress
  namespace: meeting-system
spec:
  ingressClassName: nginx
  rules:
    - host: oauth-meeting.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-svc
                port:
                  number: 9000